# Generated by Django 3.2.5 on 2022-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lynneportfolio', '0002_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('certifications_image', models.ImageField(blank=True, upload_to='certifications/')),
            ],
        ),
    ]
